#################################################################
# CLEAN HOUSEHOLD DATA
#################################################################
# Good to note is that the household data contains questions from three surveys
# 1) Stool collection survey --> individual-level data (age, sex) of those of whom a stool sample was taken
# 2) WASH survey --> household level data, answered by the household head
# 3) Healthcare utilisation survey --> individual level data
# Here for each household member, the household head is asked about the number of 
# healthcare visits in the last 30 days
# Each of these visits (per provider type) are one line of data
# Therefore there are multiple observations within a household

# with redcap_repeat_instrument, the different survey answers can be recognised
# 1) Stool collection survey --> redcap_repeat_instrument == "formulaire_collecte_de_selles"
# 2) WASH survey --> redcap_repeat_instrument == " " and redcap_event_name == "round_0_arm_1"
# 3) Healthcare utilisation survey --> redcap_repeat_instrument == "visite_structure_sanitaire"
# 4) Healthcare utilisation survey medicines --> redcap_repeat_instrument == "mdicament"


# ALL ROUNDS
################################
hh_bf = hh_bf %>% mutate(
  dob = as.Date(dob, format = "%Y-%m-%d"),
  sexe = factor(sexe, levels=c(1,2), labels=c("Male", "Female")),
  date_enquete = as.Date(date_enquete, format="%Y-%m-%d"),
  date_consentement = as.Date(date_consentement, format="%Y-%m-%d"),
  date_recuperation_selle = as.Date(date_recuperation_selle, format="%Y-%m-%d"),
  age = tolower(age),
  age = as.numeric(age),
  agegr10 = cut(age, 
                breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, Inf),
                labels = c("0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80-89", "90+"),
                include.lowest = TRUE),
  nmbre_personne_menage = as.numeric(nmbre_personne_menage),
  nbre_enf_0_5ans = as.numeric(nbre_enf_0_5ans),
  nbre_menage_conc = as.numeric(nbre_menage_conc), 
  date_enquete = as.Date(date_enquete, format="%Y-%m-%d"),
  date_consentement = as.Date(date_consentement, format="%Y-%m-%d"),
  date_recuperation_selle = as.Date(date_recuperation_selle, format="%Y-%m-%d"),
  # q1_diarrhee_prevenu___1 = factor(q1_diarrhee_prevenu___1, levels=c(0,1), labels=c("No","Yes")),        
  # q1_diarrhee_prevenu___2 = factor(q1_diarrhee_prevenu___2, levels=c(0,1), labels=c("No","Yes")),
  # q1_diarrhee_prevenu___3 = factor(q1_diarrhee_prevenu___3, levels=c(0,1), labels=c("No","Yes")),        
  # q1_diarrhee_prevenu___4 = factor(q1_diarrhee_prevenu___4, levels=c(0,1), labels=c("No","Yes")),
  # q1_diarrhee_prevenu___5 = factor(q1_diarrhee_prevenu___5, levels=c(0,1), labels=c("No","Yes")),         
  # q1_diarrhee_prevenu___6 = factor(q1_diarrhee_prevenu___6, levels=c(0,1), labels=c("No","Yes")),
  # q1_diarrhee_prevenu___7 = factor(q1_diarrhee_prevenu___7, levels=c(0,1), labels=c("No","Yes")),         
  # q1_diarrhee_prevenu___8 = factor(q1_diarrhee_prevenu___8, levels=c(0,1), labels=c("No","Yes")),
  # q1_diarrhee_prevenu___9 = factor(q1_diarrhee_prevenu___9, levels=c(0,1), labels=c("No","Yes")), 
  autr_mesur_prev_diarrhe = ifelse(autr_mesur_prev_diarrhe %in% c("certain nouriture","Certain nouriture", "CERTAIN NOURITURE",
                                                                  "Certaine nouriture", "CERTAINE NOURITURE","Certains nouriture",
                                                                  "CERTAINS NOURITURE", "Eviter certain nouriture"), "certain_food",
                                   ifelse(autr_mesur_prev_diarrhe %in% c("LAVAGE DES MAINS AVANT ET APRES LE REPAS"), "hand washing", "")),
  q2_source_princ_saison_seche = factor(q2_source_princ_saison_seche, levels=c(1:9), labels=c("Tap house", 
                                                                                              "Tap concession",
                                                                                              "Tap public/fountain", 
                                                                                              "Borehole",
                                                                                              "improved well (protected)",
                                                                                              "unimproved well (unprotected)",
                                                                                              "rainwater",
                                                                                              "surface water (ponds, dams,rivers,lakes,pits,irrigation canals)",
                                                                                              "bagged water")),
  q3_source_princ_saison_pluv = factor(q3_source_princ_saison_pluv, levels=c(1:10), labels=c("Tap house", 
                                                                                             "Tap concession",
                                                                                             "Tap public/fountain", 
                                                                                             "Borehole",
                                                                                             "improved well (protected)",
                                                                                             "unimproved well(unprotected)",
                                                                                             "rainwater",
                                                                                             "surface water (ponds, dams,rivers,lakes,pits,irrigation canals)",
                                                                                             "bagged water", "bottled water")),  
  q4_bidon_stock = factor(q4_bidon_stock, levels = c(1:3), labels=c("Yes, cans", "Yes, only one large tank", "No")),
  # q5a_bidon_ferme_rempli = factor(q5a_bidon_ferme_rempli, levels=c(1:2), labels=c("Yes", "No")),
  # q5b_bidon_ferme_vide = factor(q5b_bidon_ferme_vide, levels=c(1:2), labels=c("Yes", "No")),           
  q5c_bidon_nettoye = factor(q5c_bidon_nettoye, levels=c(1,2,3,4,6), labels=c("Yes, with soap", "Yes, with water but no soap","Yes, boiled", "No", "Other")),
  q6_traite_eau = factor(q6_traite_eau, levels = c(1:7), labels= c("No", "Yes,boiling", "Yes,cholinate/add desinfectant", "Yes, filter with cloth",
                                                                   "Yes, filter with filter", "Yes, Solar desinfection (in the sun)","Yes, decant")),               
  q7_type_inst_sanitaire = factor(q7_type_inst_sanitaire, levels = c(3,4,5), labels = c("pit latrine with slab", "pit latrine without slab", "open defecation")),
  # q8_autr_lieu_defecation___1 = factor(q8_autr_lieu_defecation___1, levels = c(0,1), labels = c("No","Yes")),      
  # q8_autr_lieu_defecation___2 = factor(q8_autr_lieu_defecation___2, levels = c(0,1), labels = c("No","Yes")),
  # q8_autr_lieu_defecation___3 = factor(q8_autr_lieu_defecation___3, levels = c(0,1), labels = c("No","Yes")),   
  # q8_autr_lieu_defecation___4 = factor(q8_autr_lieu_defecation___4, levels = c(0,1), labels = c("No","Yes")),
  # q8_autr_lieu_defecation___5 = factor(q8_autr_lieu_defecation___5, levels = c(0,1), labels = c("No","Yes")),   
  # q8_autr_lieu_defecation___6 = factor(q8_autr_lieu_defecation___6, levels = c(0,1), labels = c("No","Yes")),
  # q8_autr_lieu_defecation___7 = factor(q8_autr_lieu_defecation___7, levels = c(0,1), labels = c("No","Yes")),  
  q9_toilette_partagee = factor(q9_toilette_partagee, levels=c(1:3), labels=c("Yes, other households (non-public)", "Yes, public", "No")),             
  q10_combien_partag = as.numeric(q10_combien_partag),
  q11_dernier_nettoyage = factor(q11_dernier_nettoyage, levels=c(1:6), labels=c("<24h", ">24h, but <1week", "1-4weeks", ">1month", "Never", "Don't know")), 
  q12_elimine_selle_enf = factor(q12_elimine_selle_enf, levels = c(1:9), labels=c("Child used toilet/latrine", "Thrown/rinsed into toilet/latrine",
                                                                                  "Thrown/rinsed into drainage pit",
                                                                                  "Trown in garbage", "Buried", "Disposed in open air", 
                                                                                  "Used as manure", "Other", "NA (no child)")),
  q13_vidange_toilette = factor(q13_vidange_toilette, levels=c(1,2,4,5,7), labels=c("Has not been drained yet", "Don't know", "Removed by service provider and covered in pit",
                                                                                    "Removed by service provider (don't know where)", "Emptied by hh in uncover pit/open ground")),
  q14_produit_lavag_main = factor(q14_produit_lavag_main, levels=c(1:5), labels=c("Yes, soap", "Yes, detergent", "Yes, ash/mud/sand", "No, none available", "No, available but not used")),
  q15_lave_apr_defec = factor(q15_lave_apr_defec, levels=c(1:4), labels=c("Yes, always", "Yes, often", "No or rarerly", "Not sure")),       
  q16_lave_apr_repas = factor(q16_lave_apr_repas, levels=c(1:4), labels=c("Yes, always", "Yes, often", "No or rarerly", "Not sure")),
  q17_animaux_menage = factor(q17_animaux_menage, levels=c(1:4), labels = c("Yes, inside and outside", "Yes, outside next to house","Yes, outside in demarked area", "No")),          
  # q18_animaux_interieur___1 = factor(q18_animaux_interieur___1, levels = c(0,1), labels = c("No", "Yes")),
  # q18_animaux_interieur___2 = factor(q18_animaux_interieur___2, levels = c(0,1), labels = c("No", "Yes")),       
  # q18_animaux_interieur___3 = factor(q18_animaux_interieur___3, levels = c(0,1), labels = c("No", "Yes")),
  # q18_animaux_interieur___4 = factor(q18_animaux_interieur___4, levels = c(0,1), labels = c("No", "Yes")),       
  # q18_animaux_interieur___5 = factor(q18_animaux_interieur___5, levels = c(0,1), labels = c("No", "Yes")),
  # q18_animaux_interieur___6 = factor(q18_animaux_interieur___6, levels = c(0,1), labels = c("No", "Yes")),
  # q19_animaux_dehors___1 = factor(q19_animaux_dehors___1, levels = c(0,1), labels = c("No", "Yes")),        
  # q19_animaux_dehors___2 = factor(q19_animaux_dehors___2, levels = c(0,1), labels = c("No", "Yes")),
  # q19_animaux_dehors___3 = factor(q19_animaux_dehors___3, levels = c(0,1), labels = c("No", "Yes")),        
  # q19_animaux_dehors___4 = factor(q19_animaux_dehors___4, levels = c(0,1), labels = c("No", "Yes")),
  # q19_animaux_dehors___5 = factor(q19_animaux_dehors___5, levels = c(0,1), labels = c("No", "Yes")),         
  # q19_animaux_dehors___6 = factor(q19_animaux_dehors___6, levels = c(0,1), labels = c("No", "Yes")),
  # 
  # q20_excrement_animaux = factor(q20_excrement_animaux, levels = c(1,2,3), labels = c("Yes", "No", "Not possible to determine")),  
  # q21_animal_malade___1 = factor(q21_animal_malade___1, levels = c(0,1), labels = c("No", "Yes")),           
  # q21_animal_malade___2 = factor(q21_animal_malade___2, levels = c(0,1), labels = c("No", "Yes")),  
  # q21_animal_malade___3 = factor(q21_animal_malade___3, levels = c(0,1), labels = c("No", "Yes")),  
  # q21_animal_malade___4 = factor(q21_animal_malade___4, levels = c(0,1), labels = c("No", "Yes")),  
  # q21_animal_malade___5 = factor(q21_animal_malade___5, levels = c(0,1), labels = c("No", "Yes")),             
  # q21_animal_malade___6 = factor(q21_animal_malade___6, levels = c(0,1), labels = c("No", "Yes")),
  eau_assainissement_hygine_complete = factor(eau_assainissement_hygine_complete, levels=c(0,2), labels=c("No", "Yes")),
  piam_q1 = as.numeric(piam_q1),
  piam_q2a = as.numeric(piam_q2a),
  piam_q2b = factor(piam_q2b, levels=c(1,2), labels=c("Male", "Female")),
  piam_q6a = as.numeric(piam_q6a),
  piam_q6b = as.numeric(piam_q6b),
  piam_q6c = as.numeric(piam_q6c),
  piam_q6d = as.numeric(piam_q6d),
  piam_q6e = as.numeric(piam_q6e),
  piam_q6f = as.numeric(piam_q6f),
  piam_q6g = as.numeric(piam_q6g),
  piam_q6h = as.numeric(piam_q6h),
) %>% select(-dob) %>% rename(
  n.householdmember = "nmbre_personne_menage",
  n.child.0to5 = "nbre_enf_0_5ans",
  n.households.concession = "nbre_menage_conc",
  date.consent = "date_consentement",
  date.stool.collection = "date_recuperation_selle",
  q1.diar.prev.water.pot.covered = "q1_diarrhee_prevenu___1",
  q1.diar.prev.no.finger.in.waterglass = "q1_diarrhee_prevenu___2",
  q1.diar.prev.no.finger.in.waterglass =  "q1_diarrhee_prevenu___2",
  q1.diar.prev.utensil.to.take.water.from.pot = "q1_diarrhee_prevenu___3",    
  q1.diar.prev.cover.food = "q1_diarrhee_prevenu___4",
  q1.diar.prev.boil.water = "q1_diarrhee_prevenu___5",
  q1.diar.prev.filter.water = "q1_diarrhee_prevenu___6",
  q1.diar.prev.other = "q1_diarrhee_prevenu___7",
  q1.diar.prev.cant.be.avoided = "q1_diarrhee_prevenu___8",
  q1.diar.prev.dont.know = "q1_diarrhee_prevenu___9",
  q2.main.water.source.dry= "q2_source_princ_saison_seche",
  q3.main.water.source.rainy= "q3_source_princ_saison_pluv",
  q4.cans.storage.water= "q4_bidon_stock", 
  q5a.cans.storage.water.closed.when.filled= "q5a_bidon_ferme_rempli", 
  q5b.cans.storage.water.closed.wen.empty= "q5b_bidon_ferme_vide",          
  q5c.cans.cleaned.before.reuse= "q5c_bidon_nettoye", 
  q6.treatment.water= "q6_traite_eau", 
  q7.principle.defication= "q7_type_inst_sanitaire", 
  q8.other.defecation.flush.toiled.septic  = "q8_autr_lieu_defecation___1", 
  q8.other.defecation.pit.latrine.ventilation = "q8_autr_lieu_defecation___2",
  q8.other.defecation.pit.latrine.slab = "q8_autr_lieu_defecation___3",   
  q8.other.defecation.pit.latrine.no.slab = "q8_autr_lieu_defecation___4",
  q8.other.defecation.open.defecation = "q8_autr_lieu_defecation___5",   
  q8.other.defecation.other = "q8_autr_lieu_defecation___6",
  q8.other.defecation.none = "q8_autr_lieu_defecation___7",
  q9.shared.toilet= "q9_toilette_partagee",
  q10.n.shared.toilet= "q10_combien_partag",
  q11.toilet.last.cleaned= "q11_dernier_nettoyage",
  q12.disposal.child.stool= "q12_elimine_selle_enf",
  q13.disposal.latrine.pit= "q13_vidange_toilette",
  q14.handwashing.product= "q14_produit_lavag_main",
  q15.handwashing.defecation= "q15_lave_apr_defec",
  q16.handwashing.meals= "q16_lave_apr_repas",
  q17.animals.around.household= "q17_animaux_menage",
  q18.animal.inside.cow = "q18_animaux_interieur___1",
  q18.animal.inside.sheep.goat = "q18_animaux_interieur___2",       
  q18.animal.inside.pig = "q18_animaux_interieur___3",
  q18.animal.inside.donkey.horse = "q18_animaux_interieur___4",       
  q18.animal.inside.chicken.goose.duck = "q18_animaux_interieur___5",
  q18.animal.inside.other = "q18_animaux_interieur___6",
  q19.animal.outside.cow = "q19_animaux_dehors___1",
  q19.animal.outside.sheep.goat = "q19_animaux_dehors___2",       
  q19.animal.outside.pig = "q19_animaux_dehors___3",
  q19.animal.outside.donkey.horse = "q19_animaux_dehors___4",       
  q19.animal.outside.chicken.goose.duck = "q19_animaux_dehors___5",
  q19.animal.outside.other = "q19_animaux_dehors___6",
  q20.animal.excrement.floor= q20_excrement_animaux, 
  q21.when.animal.ill.treatment.with.vet = "q21_animal_malade___1",           
  q21.when.animal.ill.treatment.without.vet= "q21_animal_malade___2",  
  q21.when.animal.ill.sell.bucher = "q21_animal_malade___3",  
  q21.when.animal.ill.slaugter.eat.at.home= "q21_animal_malade___4",  
  q21.when.animal.ill.dies.burie.dispose = "q21_animal_malade___5",             
  q21.when_animal.ill.dies.eat.at.home= "q21_animal_malade___6",
  piam.q1.n.athome.when.survey = "piam_q1",
  piam.q2a.athome.age.random.selected.person = "piam_q2a",
  piam.q2a.athome.sex.random.selected.person = "piam_q2b",
  piam.q3.heard.about.trial.activities = "piam_q3",
  piam.q4.partic.atleastone.trial.activities = "piam_q4",
  piam.q5.perc.key.topic.hwashing.use.soap = "piam_q5___1",
  piam.q5.perc.key.topic.hwashing.when = "piam_q5___2",
  piam.q5.perc.key.topic.abx.what.and.role = "piam_q5___3",
  piam.q5.perc.key.topic.abx.correct.use= "piam_q5___4",
  piam.q5.perc.key.topic.seek.care.no.self.med = "piam_q5___5",
  piam.q5.perc.key.topic.good.sani.latr.wastw= "piam_q5___6",
  piam.q5.perc.key.topic.drink.treat.or.borehole.water= "piam_q5___7",
  piam.q5.perc.key.topic.protect.store.water.clean.container= "piam_q5___8",
  piam.q5.perceived.key.topic.handwashing= "piam_q6a",
  piam.q6.freq.partic.hwashing.public = "piam_q6b",
  piam.q6.freq.partic.abx.use.public = "piam_q6c",
  piam.q6.freq.partic.hwashing.athome = "piam_q6d",
  piam.q6.freq.partic.abx.use.athome= "piam_q6e",
  piam.q6.freq.partic.abx.use.adhoc= "piam_q6f",
  piam.q6.freq.partic.defication.adhoc= "piam_q6g",
  piam.q6.freq.partic.defication.public= "piam_q6h"
)

table(hh_bf$agegr10)

# Link village and cluster data to household survey
hh_bf$data_row = c(1:nrow(hh_bf)) # This variable we can use for identifying back those individuals that had a sample taken
hh_bf$village = substr(hh_bf$menage_id, start = 1, stop = 2)
hh_bf = merge(hh_bf, villages, by="village")
names(hh_bf)

names(hh_bf) = gsub("_",".",names(hh_bf))
hh_bf = hh_bf %>%
  rename(menage_id = "menage.id",
         village_name = "village.name",
         redcap_event_name = "redcap.event.name")

# Select relevant WASH variables from the household survey
################################################################################################

# variables excluding healthcare seeking behaviour survey questions (and related medicine use); as these
# are not 1 observation per household
hh_bf_wash = hh_bf %>% select(data.row,menage_id,village, village_name, intervention.text,   
                              redcap_event_name,
                              date.enquete,
                              groupe,
                              n.householdmember, 
                              n.child.0to5,
                              n.households.concession,
                              q1.diar.prev.water.pot.covered,
                              q1.diar.prev.no.finger.in.waterglass,                    
                              q1.diar.prev.utensil.to.take.water.from.pot, q1.diar.prev.cover.food,                                  
                              q1.diar.prev.boil.water, q1.diar.prev.filter.water,                               
                              q1.diar.prev.other,q1.diar.prev.cant.be.avoided,                            
                              q1.diar.prev.dont.know, autr.mesur.prev.diarrhe,                                  
                              q2.main.water.source.dry, q3.main.water.source.rainy,                              
                              q4.cans.storage.water, q5a.cans.storage.water.closed.when.filled,                                   
                              q5b.cans.storage.water.closed.wen.empty, q5c.cans.cleaned.before.reuse,                                        
                              q6.treatment.water, q6.autre.traitmen.eau,                                    
                              q7.principle.defication, q7.autr.typ.ins.sanitair,                                 
                              q8.other.defecation.flush.toiled.septic, q8.other.defecation.pit.latrine.ventilation,             
                              q8.other.defecation.pit.latrine.slab, q8.other.defecation.pit.latrine.no.slab,                  
                              q8.other.defecation.open.defecation, q8.other.defecation.other,                                
                              q8.other.defecation.none, q8.autre.preciser,                                        
                              q9.shared.toilet, q10.n.shared.toilet,                                       
                              q11.toilet.last.cleaned, q12.disposal.child.stool,                                    
                              q12.autre.preciser, q13.disposal.latrine.pit,                                     
                              q13.autre.preciser, q14.handwashing.product,                                   
                              q15.handwashing.defecation, q16.handwashing.meals,                                       
                              q17.animals.around.household, q18.animal.inside.cow,                                    
                              q18.animal.inside.sheep.goat, q18.animal.inside.pig,                                    
                              q18.animal.inside.donkey.horse, q18.animal.inside.chicken.goose.duck,                     
                              q18.animal.inside.other,q18.autre.specifie,                                       
                              q19.animal.outside.cow, q19.animal.outside.sheep.goat,                             
                              q19.animal.outside.pig,q19.animal.outside.donkey.horse,                           
                              q19.animal.outside.chicken.goose.duck, q19.animal.outside.other,                                  
                              q19.autre.specifie, q20.animal.excrement.floor,                                    
                              q21.when.animal.ill.treatment.with.vet, q21.when.animal.ill.treatment.without.vet,                
                              q21.when.animal.ill.sell.bucher,q21.when.animal.ill.slaugter.eat.at.home,                     
                              q21.when.animal.ill.dies.burie.dispose,q21.when.animal.ill.dies.eat.at.home,                                
                              eau.assainissement.hygine.complete,
                              piam.q1.n.athome.when.survey,
                              piam.q2a.athome.age.random.selected.person,
                              piam.q2a.athome.sex.random.selected.person,
                              piam.q3.heard.about.trial.activities,
                              piam.q4.partic.atleastone.trial.activities,
                              piam.q5.perc.key.topic.hwashing.use.soap,
                              piam.q5.perc.key.topic.hwashing.when,
                              piam.q5.perc.key.topic.abx.what.and.role,
                              piam.q5.perc.key.topic.abx.correct.use,
                              piam.q5.perc.key.topic.seek.care.no.self.med,
                              piam.q5.perc.key.topic.good.sani.latr.wastw,
                              piam.q5.perc.key.topic.drink.treat.or.borehole.water,
                              piam.q5.perc.key.topic.protect.store.water.clean.container,
                              piam.q5.perceived.key.topic.handwashing,
                              piam.q6.freq.partic.hwashing.public,
                              piam.q6.freq.partic.abx.use.public,
                              piam.q6.freq.partic.hwashing.athome,
                              piam.q6.freq.partic.abx.use.athome,
                              piam.q6.freq.partic.abx.use.adhoc,
                              piam.q6.freq.partic.defication.adhoc,
                              piam.q6.freq.partic.defication.public) %>%
  filter(!is.na(date.enquete)) # Denominator data (i.e. people tested for esbl) for R0

hh_bf_wash_r3 = hh_bf %>% filter(is.na(redcap.repeat.instrument) & redcap_event_name=="round_3_arm_1") %>%
  select(data.row,menage_id,village, village_name, intervention.text,   
         redcap_event_name,
         date.enquete,
         groupe,
         n.householdmember, 
         n.child.0to5,
         n.households.concession,
         q1.diar.prev.water.pot.covered,
         q1.diar.prev.no.finger.in.waterglass,                    
         q1.diar.prev.utensil.to.take.water.from.pot, q1.diar.prev.cover.food,                                  
         q1.diar.prev.boil.water, q1.diar.prev.filter.water,                               
         q1.diar.prev.other,q1.diar.prev.cant.be.avoided,                            
         q1.diar.prev.dont.know, autr.mesur.prev.diarrhe,                                  
         q2.main.water.source.dry, q3.main.water.source.rainy,                              
         q4.cans.storage.water, q5a.cans.storage.water.closed.when.filled,                                   
         q5b.cans.storage.water.closed.wen.empty, q5c.cans.cleaned.before.reuse,                                        
         q6.treatment.water, q6.autre.traitmen.eau,                                    
         q7.principle.defication, q7.autr.typ.ins.sanitair,                                 
         q8.other.defecation.flush.toiled.septic, q8.other.defecation.pit.latrine.ventilation,             
         q8.other.defecation.pit.latrine.slab, q8.other.defecation.pit.latrine.no.slab,                  
         q8.other.defecation.open.defecation, q8.other.defecation.other,                                
         q8.other.defecation.none, q8.autre.preciser,                                        
         q9.shared.toilet, q10.n.shared.toilet,                                       
         q11.toilet.last.cleaned, q12.disposal.child.stool,                                    
         q12.autre.preciser, q13.disposal.latrine.pit,                                     
         q13.autre.preciser, q14.handwashing.product,                                   
         q15.handwashing.defecation, q16.handwashing.meals,                                       
         q17.animals.around.household, q18.animal.inside.cow,                                    
         q18.animal.inside.sheep.goat, q18.animal.inside.pig,                                    
         q18.animal.inside.donkey.horse, q18.animal.inside.chicken.goose.duck,                     
         q18.animal.inside.other,q18.autre.specifie,                                       
         q19.animal.outside.cow, q19.animal.outside.sheep.goat,                             
         q19.animal.outside.pig,q19.animal.outside.donkey.horse,                           
         q19.animal.outside.chicken.goose.duck, q19.animal.outside.other,                                  
         q19.autre.specifie, q20.animal.excrement.floor,                                    
         q21.when.animal.ill.treatment.with.vet, q21.when.animal.ill.treatment.without.vet,                
         q21.when.animal.ill.sell.bucher,q21.when.animal.ill.slaugter.eat.at.home,                     
         q21.when.animal.ill.dies.burie.dispose,q21.when.animal.ill.dies.eat.at.home,                                
         eau.assainissement.hygine.complete,
         piam.q1.n.athome.when.survey,
         piam.q2a.athome.age.random.selected.person,
         piam.q2a.athome.sex.random.selected.person,
         piam.q3.heard.about.trial.activities,
         piam.q4.partic.atleastone.trial.activities,
         piam.q5.perc.key.topic.hwashing.use.soap,
         piam.q5.perc.key.topic.hwashing.when,
         piam.q5.perc.key.topic.abx.what.and.role,
         piam.q5.perc.key.topic.abx.correct.use,
         piam.q5.perc.key.topic.seek.care.no.self.med,
         piam.q5.perc.key.topic.good.sani.latr.wastw,
         piam.q5.perc.key.topic.drink.treat.or.borehole.water,
         piam.q5.perc.key.topic.protect.store.water.clean.container,
         piam.q5.perceived.key.topic.handwashing,
         piam.q6.freq.partic.hwashing.public,
         piam.q6.freq.partic.abx.use.public,
         piam.q6.freq.partic.hwashing.athome,
         piam.q6.freq.partic.abx.use.athome,
         piam.q6.freq.partic.abx.use.adhoc,
         piam.q6.freq.partic.defication.adhoc,
         piam.q6.freq.partic.defication.public) 
# Denominator data (i.e. people tested for esbl) for R3


hh_bf_wash_r3 = merge(hh_bf_wash_r3, hh_bf_wash %>% select(menage_id, n.householdmember,n.child.0to5, n.households.concession), by="menage_id",all.x=T) 
hh_bf_wash_r3 = hh_bf_wash_r3 %>%
  mutate(n.householdmember.x = n.householdmember.y,
         n.child.0to5.x = n.child.0to5.y,
         n.households.concession.x = n.households.concession.y) %>%
  select(-c(n.householdmember.y,n.child.0to5.y, n.households.concession.y)) %>%
  rename(n.householdmember = "n.householdmember.x",
         n.child.0to5 = "n.child.0to5.x",
         n.households.concession ="n.households.concession.x")
